Repository refereelabs/betafold, pull requests merged in 2025-02, with the labels that each got.

#6 [I-1] Scaffolding for Documentation
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: Approved

#9 [8] Implements a C++ Linter
  .gitignore
  .pre-commit-config.yaml
  CMakeLists.txt
  CONTRIBUTING.md
  docs/transformers_analogs.txt
  setup.py
  src/main.cpp
Labels: Feature, Assigned, Needs Review

#21 [18] Changed "Accepted" to "Approved" in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Needs Review
